    - name: create template
      template: 
        src: hosts.j2
        dest: /etc/myhosts
      register: output

    - name: output the results
      debug:
        msg: "{{ lookup('template', './hosts.j2', comment_start_string='[%', comment_end_string='%]' ) }}"
      
